version: '3.4'

services:
  teste:
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'Secret=3ce1637ed40041cd94d4853d3e766c4d'
    ports:
      - "5557:80"

  autentica:
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'Secret=3ce1637ed40041cd94d4853d3e766c4d'
      - 'ConnectionStrings:Database=Server=localhost;Port=5432;Database=backoffice;User Id=admin@localhost;Password=root;SSL Mode=Require;'
    ports:
      - "5556:80"

  gateway:
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'Secret=3ce1637ed40041cd94d4853d3e766c4d'
    ports:
      - "80:80"


