version: '3.4'

services:
  gateway:
    image: microservicos.azurecr.io/microservicosgatewayapi:latest
    container_name: gateway
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'Secret=3ce1637ed40041cd94d4853d3e766c4d'
    ports:
      - "80:80"

  autentica:
    image: microservicos.azurecr.io/microservicosautenticaapi:latest
    container_name: autentica
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'Secret=3ce1637ed40041cd94d4853d3e766c4d'
      - 'ConnectionStrings:Database=Server=localhost;Port=5432;Database=backoffice;User Id=admin@localhost;Password=root;SSL Mode=Require;'
    ports:
      - "80:80"

  teste:
    image: microservicos.azurecr.io/microservicostesteapi:latest
    container_name: teste
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'Secret=3ce1637ed40041cd94d4853d3e766c4d'
    ports:
      - "80:80"
